# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
db.list_collection_names()

['establishments', 'data']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Create a dictionary for the new restaurant data
new_rest = {"Penang Flavours": """{
    "BusinessName":"Penang Flavours",
    "BusinessType":"Restaurant/Cafe/Canteen",
    "BusinessTypeID":"",
    "AddressLine1":"Penang Flavours",
    "AddressLine2":"146A Plumstead Rd",
    "AddressLine3":"London",
    "AddressLine4":"",
    "PostCode":"SE18 7DY",
    "Phone":"",
    "LocalAuthorityCode":"511",
    "LocalAuthorityName":"Greenwich",
    "LocalAuthorityWebSite":"http://www.royalgreenwich.gov.uk",
    "LocalAuthorityEmailAddress":"health@royalgreenwich.gov.uk",
    "scores":{
        "Hygiene":"",
        "Structural":"",
        "ConfidenceInManagement":""
    },
    "SchemeType":"FHRS",
    "geocode":{
        "longitude":"0.08384000",
        "latitude":"51.49014200"
    },
    "RightToReply":"",
    "Distance":4623.9723280747176,
    "NewRatingPending":True
}"""}
# Insert the new restaurant into the collection
establishments.insert_one(new_rest)

In [7]:
# Find the inserted document using its _id
penang_flavours = establishments.find({"BusinessName":"Penang Flavours"})

# Print the inserted document
pprint(penang_flavours)

<pymongo.cursor.Cursor object at 0x000002380F6105E0>

In [8]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': 20}
result_cursor = establishments.find(query)

# Use count() to display the number of documents contained in the result
num_documents = result_cursor.count()
print("Number of documents:", num_documents)

# Display the first document in the results using pprint
first_document = result_cursor.next()
print("First document:")
pprint(first_document)

# Convert the result to a Pandas DataFrame
result_cursor = establishments.find(query)  # Reset cursor position
df = pd.DataFrame(list(result_cursor))

# Print the number of rows in the DataFrame
print("Number of rows in DataFrame:", len(df))

# Display the first 10 rows
print("First 10 rows of DataFrame:")
df.head(10)

C:\Users\aKost\AppData\Local\Temp\ipykernel_18500\2902147253.py:6: DeprecationWarning: count is deprecated. Use Collection.count_documents instead.
  num_documents = result_cursor.count()

Number of documents: 82
First document:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6616ec0252bb97ed27858028'),
 'geocode': {'latitude': None, 'longitude': None},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}
Number of rows in DataFrame: 82
First 10 rows of DataFrame:

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,6616ec0252bb97ed27858028,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,6616ec0252bb97ed278583a9,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,6616ec0252bb97ed278586b3,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,6616ec0252bb97ed278588a1,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,6616ec0252bb97ed278588b0,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,6616ec0252bb97ed2785924f,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,6616ec0252bb97ed27859470,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,6616ec0252bb97ed2785a99b,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,6616ec0252bb97ed2785addf,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': None, 'latitude': None}",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,6616ec0252bb97ed2785b5f1,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': None, 'latitude': None}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [9]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {
    'LocalAuthorityName': 'London',
    'RatingValue': {'$gte': 4}
}

# Use count_documents to display the number of documents in the result
num_documents = establishments.count_documents(query)
print("Number of documents:", num_documents)

# Display the first document in the results using pprint
first_document = establishments.find_one(query)
print("First document:")
pprint(first_document)

# Convert the result to a Pandas DataFrame
result_cursor = establishments.find(query)
df = pd.DataFrame(list(result_cursor))

# Display the number of rows in the DataFrame
print("Number of rows in DataFrame:", len(df))

# Display the first 10 rows of the DataFrame
print("First 10 rows of DataFrame:")
df.head(10)

Number of documents: 0
First document:
None
Number of rows in DataFrame: 0
First 10 rows of DataFrame:

Empty DataFrame
Columns: []
Index: []

In [10]:
penang_flavours = establishments.find_one({'BusinessName': 'Penang Flavours'})
pprint(penang_flavours)

{'AddressLine1': 'Penang Flavours',
 'AddressLine2': '146A Plumstead Rd',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'BusinessName': 'Penang Flavours',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': '',
 'Distance': 4623.972328074718,
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': True,
 'Phone': '',
 'PostCode': 'SE18 7DY',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66170135c958f46c107da589'),
 'geocode': {'latitude': '51.49014200', 'longitude': '0.08384000'},
 'scores': {'ConfidenceInManagement': '', 'Hygiene': '', 'Structural': ''}}

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [11]:
# Create a dictionary for the new restaurant data
new_rest = {
    "BusinessName": "Penang Flavours",
    "BusinessType": "Restaurant/Cafe/Canteen",
    "BusinessTypeID": "",
    "AddressLine1": "Penang Flavours",
    "AddressLine2": "146A Plumstead Rd",
    "AddressLine3": "London",
    "AddressLine4": "",
    "PostCode": "SE18 7DY",
    "Phone": "",
    "LocalAuthorityCode": "511",
    "LocalAuthorityName": "Greenwich",
    "LocalAuthorityWebSite": "http://www.royalgreenwich.gov.uk",
    "LocalAuthorityEmailAddress": "health@royalgreenwich.gov.uk",
    "scores": {
        "Hygiene": "",
        "Structural": "",
        "ConfidenceInManagement": ""
    },
    "SchemeType": "FHRS",
    "geocode": {
        "longitude": "0.08384000",
        "latitude": "51.49014200"
    },
    "RightToReply": "",
    "Distance": 4623.9723280747176,
    "NewRatingPending": True
}

# Insert the new restaurant into the collection
establishments.insert_one(new_rest)

In [12]:
penang_flavours = establishments.find_one({'BusinessName': 'Penang Flavours'})

if penang_flavours is not None:
    geocode = penang_flavours.get('geocode', {})
    latitude_str = geocode.get('latitude')
    longitude_str = geocode.get('longitude')

    try:
        latitude = float(latitude_str)
        longitude = float(longitude_str)
    except (TypeError, ValueError):
        latitude = None
        longitude = None

    if latitude is not None and longitude is not None:
        degree_search = 0.01

        query = {
            'RatingValue': 5,
            'geocode.latitude': {'$gte': latitude - degree_search, '$lte': latitude + degree_search},
            'geocode.longitude': {'$gte': longitude - degree_search, '$lte': longitude + degree_search}
        }

        sort = [('scores.Hygiene', 1)]  # Sort by hygiene score in ascending order

        limit = 5

        result_cursor = establishments.find(query).sort(sort).limit(limit)

        num_documents = establishments.count_documents(query)
        print("Number of documents:", num_documents)

        first_document = result_cursor.next()
        print("First document:")
        pprint(first_document)

        result_cursor = establishments.find(query).sort(sort).limit(limit)
        df = pd.DataFrame(list(result_cursor))

        print("Number of rows in DataFrame:", len(df))

        print("First 10 rows of DataFrame:")
        df.head(10)
    else:
        print("Latitude or longitude not available for 'Penang Flavours'.")
else:
    print("No document found with BusinessName 'Penang Flavours'.")

Number of documents: 0

StopIteration:

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [15]:
pipeline = [
    # Match establishments with a hygiene score of 0
    {"$match": {"scores.Hygiene": 0}},
    # Group the matches by Local Authority
    {"$group": {"_id": "$LocalAuthorityName", "count": {"$sum": 1}}},
    # Sort the matches from highest to lowest
    {"$sort": {"count": -1}}
]
result = establishments.aggregate(pipeline)

num_documents = len(list(result))
print("Number of documents:", num_documents)

result = establishments.aggregate(pipeline)
print("First 10 results:")
for i, doc in enumerate(result):
    if i >= 10:
        break
    pprint(doc)

Number of documents: 55
First 10 results:
{'_id': 'Thanet', 'count': 2260}
{'_id': 'Greenwich', 'count': 1764}
{'_id': 'Maidstone', 'count': 1426}
{'_id': 'Newham', 'count': 1422}
{'_id': 'Swale', 'count': 1372}
{'_id': 'Chelmsford', 'count': 1360}
{'_id': 'Medway', 'count': 1344}
{'_id': 'Bexley', 'count': 1214}
{'_id': 'Southend-On-Sea', 'count': 1172}
{'_id': 'Tendring', 'count': 1084}

In [16]:
result = list(establishments.aggregate(pipeline))

df = pd.DataFrame(result)

num_rows = len(df)
print("Number of rows in DataFrame:", num_rows)

print("First 10 rows of DataFrame:")
df.head(10)

Number of rows in DataFrame: 55
First 10 rows of DataFrame:

               _id  count
0           Thanet   2260
1        Greenwich   1764
2        Maidstone   1426
3           Newham   1422
4            Swale   1372
5       Chelmsford   1360
6           Medway   1344
7           Bexley   1214
8  Southend-On-Sea   1172
9         Tendring   1084